-- MySQL Script generated by MySQL Workbench
-- Sun Dec 14 06:11:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eparkingdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eparkingdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eparkingdb` DEFAULT CHARACTER SET utf8 ;
USE `eparkingdb` ;

-- -----------------------------------------------------
-- Table `eparkingdb`.`parking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eparkingdb`.`parking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eparkingdb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eparkingdb`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `permission` VARCHAR(45) NOT NULL,
  `loginAttempt` INT NOT NULL,
  `userLock` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eparkingdb`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eparkingdb`.`reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `startTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  `parking_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservation_parking_idx` (`parking_id` ASC) VISIBLE,
  INDEX `fk_reservation_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_parking`
    FOREIGN KEY (`parking_id`)
    REFERENCES `eparkingdb`.`parking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `eparkingdb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
